// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// An object to represent AAC audio encoding settings.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.AacAudio")]
    public partial class AacAudio : Audio
    {
        /// <summary>
        /// Initializes a new instance of the AacAudio class.
        /// </summary>
        public AacAudio()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AacAudio class.
        /// </summary>
        /// <param name="label">Gets or sets the codec label.</param>
        /// <param name="channels">Gets or sets number of channels in the
        /// Audio.</param>
        /// <param name="samplingRate">Gets or sets the sampling rate to use
        /// for encoding.</param>
        /// <param name="bitrate">Gets or sets the bitrate of the encoded
        /// audio.</param>
        /// <param name="profile">Gets or sets the audio profile. Possible
        /// values include: 'AacLc', 'HeAacV1', 'HeAacV2'</param>
        public AacAudio(string label = default(string), int? channels = default(int?), int? samplingRate = default(int?), int? bitrate = default(int?), AacAudioProfile? profile = default(AacAudioProfile?))
            : base(label, channels, samplingRate, bitrate)
        {
            Profile = profile;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the audio profile. Possible values include: 'AacLc',
        /// 'HeAacV1', 'HeAacV2'
        /// </summary>
        [JsonProperty(PropertyName = "profile")]
        public AacAudioProfile? Profile { get; set; }

    }
}
