// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The Asset storage encryption key.
    /// </summary>
    public partial class AssetStorageEncryptionKey
    {
        /// <summary>
        /// Initializes a new instance of the AssetStorageEncryptionKey class.
        /// </summary>
        public AssetStorageEncryptionKey()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetStorageEncryptionKey class.
        /// </summary>
        /// <param name="storageEncryptionKey">The Asset storage encryption
        /// key.</param>
        public AssetStorageEncryptionKey(string storageEncryptionKey = default(string))
        {
            StorageEncryptionKey = storageEncryptionKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the Asset storage encryption key.
        /// </summary>
        [JsonProperty(PropertyName = "storageEncryptionKey")]
        public string StorageEncryptionKey { get; set; }

    }
}
