// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// An audio indexer preset that analyzes the audio.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.AudioIndexerPreset")]
    public partial class AudioIndexerPreset : Preset
    {
        /// <summary>
        /// Initializes a new instance of the AudioIndexerPreset class.
        /// </summary>
        public AudioIndexerPreset()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AudioIndexerPreset class.
        /// </summary>
        /// <param name="audioLanguage">Gets or sets the audio language for the
        /// video. Typically in the format of "language code-country/region"
        /// (e.g: en-US)</param>
        public AudioIndexerPreset(string audioLanguage = default(string))
        {
            AudioLanguage = audioLanguage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the audio language for the video. Typically in the
        /// format of "language code-country/region" (e.g: en-US)
        /// </summary>
        [JsonProperty(PropertyName = "audioLanguage")]
        public string AudioLanguage { get; set; }

    }
}
