// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Object to represent closed caption stream selection.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.ClosedCaptionStream")]
    public partial class ClosedCaptionStream : StreamSelection
    {
        /// <summary>
        /// Initializes a new instance of the ClosedCaptionStream class.
        /// </summary>
        public ClosedCaptionStream()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClosedCaptionStream class.
        /// </summary>
        /// <param name="fileIndex">Gets the file index where the stream is
        /// present.</param>
        /// <param name="streamIndex">Gets the stream index.</param>
        /// <param name="isAbsoluteStreamIndex">Gets a value indicating whether
        /// the stream index is absolute or relative to the stream
        /// type.</param>
        /// <param name="streamSelectionMode">Gets the stream selection mode.
        /// Possible values include: 'SelectionNotSet',
        /// 'SelectHighestBitrateStream', 'SelectLowestBitrateStream',
        /// 'SelectAllStreams'</param>
        public ClosedCaptionStream(int fileIndex, int streamIndex, bool? isAbsoluteStreamIndex = default(bool?), StreamSelectionMode? streamSelectionMode = default(StreamSelectionMode?))
            : base(fileIndex, streamIndex, isAbsoluteStreamIndex, streamSelectionMode)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public override void Validate()
        {
            base.Validate();
        }
    }
}
