// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines values for H264VideoProfile.
    /// </summary>
    /// <summary>
    /// Determine base value for a given allowed value if exists, else return
    /// the value itself
    /// </summary>
    [JsonConverter(typeof(H264VideoProfileConverter))]
    public struct H264VideoProfile : System.IEquatable<H264VideoProfile>
    {
        private H264VideoProfile(string underlyingValue)
        {
            UnderlyingValue=underlyingValue;
        }

        /// <summary>
        /// The encoder auto decide the appropriate profile
        /// </summary>
        public static readonly H264VideoProfile Auto = "Auto";

        /// <summary>
        /// Baseline H264 video profile
        /// </summary>
        public static readonly H264VideoProfile Baseline = "Baseline";

        /// <summary>
        /// Main H264 video profile
        /// </summary>
        public static readonly H264VideoProfile Main = "Main";

        /// <summary>
        /// High H264 video profile.
        /// </summary>
        public static readonly H264VideoProfile High = "High";

        /// <summary>
        /// High10 H264 video profile.
        /// </summary>
        public static readonly H264VideoProfile High10 = "High10";

        /// <summary>
        /// High 4 2 2 H264 video profile.
        /// </summary>
        public static readonly H264VideoProfile High422 = "High422";

        /// <summary>
        /// High 4 4 4 H264 video profile.
        /// </summary>
        public static readonly H264VideoProfile High444 = "High444";


        /// <summary>
        /// Underlying value of enum H264VideoProfile
        /// </summary>
        private readonly string UnderlyingValue;

        /// <summary>
        /// Returns string representation for H264VideoProfile
        /// </summary>
        public override string ToString()
        {
            return UnderlyingValue.ToString();
        }

        /// <summary>
        /// Compares enums of type H264VideoProfile
        /// </summary>
        public bool Equals(H264VideoProfile e)
        {
            return UnderlyingValue.Equals(e.UnderlyingValue);
        }

        /// <summary>
        /// Implicit operator to convert string to H264VideoProfile
        /// </summary>
        public static implicit operator H264VideoProfile(string value)
        {
            return new H264VideoProfile(value);
        }

        /// <summary>
        /// Implicit operator to convert H264VideoProfile to string
        /// </summary>
        public static implicit operator string(H264VideoProfile e)
        {
            return e.UnderlyingValue;
        }

        /// <summary>
        /// Overriding == operator for enum H264VideoProfile
        /// </summary>
        public static bool operator == (H264VideoProfile e1, H264VideoProfile e2)
        {
            return e2.Equals(e1);
        }

        /// <summary>
        /// Overriding != operator for enum H264VideoProfile
        /// </summary>
        public static bool operator != (H264VideoProfile e1, H264VideoProfile e2)
        {
            return !e2.Equals(e1);
        }

        /// <summary>
        /// Overrides Equals operator for H264VideoProfile
        /// </summary>
        public override bool Equals(object obj)
        {
            return obj is H264VideoProfile && Equals((H264VideoProfile)obj);
        }

        /// <summary>
        /// Returns for hashCode H264VideoProfile
        /// </summary>
        public override int GetHashCode()
        {
            return UnderlyingValue.GetHashCode();
        }

    }
}
