// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Generates image file output.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.ImageFormat")]
    public partial class ImageFormat : Format
    {
        /// <summary>
        /// Initializes a new instance of the ImageFormat class.
        /// </summary>
        public ImageFormat()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ImageFormat class.
        /// </summary>
        /// <param name="filenamePattern">Gets or sets the pattern of the
        /// filename to use excluding the extension. REVIEW: List "macros" that
        /// can be used and give examples.</param>
        public ImageFormat(string filenamePattern = default(string))
            : base(filenamePattern)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
