// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class JobCollection
    {
        /// <summary>
        /// Initializes a new instance of the JobCollection class.
        /// </summary>
        public JobCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JobCollection class.
        /// </summary>
        public JobCollection(IList<Job> value = default(IList<Job>), int? odatacount = default(int?), string odatanextLink = default(string))
        {
            Value = value;
            Odatacount = odatacount;
            OdatanextLink = odatanextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<Job> Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "@odata.count")]
        public int? Odatacount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "@odata.nextLink")]
        public string OdatanextLink { get; set; }

    }
}
