// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// This represents a layer in the JpgImage class.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.JpgLayer")]
    public partial class JpgLayer : Layer
    {
        /// <summary>
        /// Initializes a new instance of the JpgLayer class.
        /// </summary>
        public JpgLayer()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JpgLayer class.
        /// </summary>
        /// <param name="width">Gets or sets width of video in pixels for this
        /// layer.</param>
        /// <param name="height">Gets or sets height of video in pixels for
        /// this layer.</param>
        /// <param name="condition">Gets or sets the predicate to be evaluated
        /// before encoding this layer.</param>
        /// <param name="label">Gets or sets the label for this layer.</param>
        /// <param name="quality">Gets or sets the compression quality of the
        /// JPEG output. Range is from 0-100 and the default is 70.</param>
        public JpgLayer(string width = default(string), string height = default(string), string condition = default(string), string label = default(string), int? quality = default(int?))
            : base(width, height, condition, label)
        {
            Quality = quality;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the compression quality of the JPEG output. Range is
        /// from 0-100 and the default is 70.
        /// </summary>
        [JsonProperty(PropertyName = "quality")]
        public int? Quality { get; set; }

    }
}
