// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The parameters to the list SAS requet.
    /// </summary>
    public partial class ListContainerSasInput
    {
        /// <summary>
        /// Initializes a new instance of the ListContainerSasInput class.
        /// </summary>
        public ListContainerSasInput()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ListContainerSasInput class.
        /// </summary>
        /// <param name="permissions">The permissions to set on the SAS URL.
        /// Possible values include: 'Read', 'ReadWrite',
        /// 'ReadWriteDelete'</param>
        /// <param name="expiryTime">The SAS URL expiry time.</param>
        public ListContainerSasInput(AssetContainerPermission? permissions = default(AssetContainerPermission?), System.DateTimeOffset? expiryTime = default(System.DateTimeOffset?))
        {
            Permissions = permissions;
            ExpiryTime = expiryTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the permissions to set on the SAS URL. Possible values
        /// include: 'Read', 'ReadWrite', 'ReadWriteDelete'
        /// </summary>
        [JsonProperty(PropertyName = "permissions")]
        public AssetContainerPermission? Permissions { get; set; }

        /// <summary>
        /// Gets or sets the SAS URL expiry time.
        /// </summary>
        [JsonProperty(PropertyName = "expiryTime")]
        public System.DateTimeOffset? ExpiryTime { get; set; }

    }
}
