// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The Asset container SAS.
    /// </summary>
    public partial class AssetContainerSas
    {
        /// <summary>
        /// Initializes a new instance of the AssetContainerSas class.
        /// </summary>
        public AssetContainerSas()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetContainerSas class.
        /// </summary>
        /// <param name="assetContainerSasUrls">The list of Asset container SAS
        /// URLs.</param>
        public AssetContainerSas(IList<string> assetContainerSasUrls = default(IList<string>))
        {
            AssetContainerSasUrls = assetContainerSasUrls;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the list of Asset container SAS URLs.
        /// </summary>
        [JsonProperty(PropertyName = "assetContainerSasUrls")]
        public IList<string> AssetContainerSasUrls { get; set; }

    }
}
