// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// An object to indicate audio overlay.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.AudioOverlay")]
    public partial class AudioOverlay : Overlay
    {
        /// <summary>
        /// Initializes a new instance of the AudioOverlay class.
        /// </summary>
        public AudioOverlay()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AudioOverlay class.
        /// </summary>
        /// <param name="inputLabel">Gets or sets the label of the Input used
        /// for the Overlay.   The Input must specify exactly one file to
        /// use.</param>
        /// <param name="inputLoop">Gets or sets a value indicating whether the
        /// overlay is looped to match the duration of the input media.</param>
        /// <param name="start">Gets or sets the duration in the video at which
        /// the overlay starts. This is relative to the clip start if one is
        /// specified in a job. Default is from the beginning of the
        /// video.</param>
        /// <param name="end">Gets or sets the duration in the video at which
        /// the overlay ends.  This is relative to the clip start if specified
        /// in a job. Default is till the end of the video if InputLoop is
        /// true. else the duration of the overlay.</param>
        /// <param name="fadeInDuration">Gets or sets the duration for how long
        /// the fade in happens. Default is no fade in.</param>
        /// <param name="fadeOutDuration">Gets or sets the duration for how
        /// long the fade out happens. Default is no fade out.</param>
        /// <param name="audioGainLevel">Gets or sets the gain level of audio
        /// in the overlay. Defaults to a value of 1.0.</param>
        public AudioOverlay(string inputLabel = default(string), bool? inputLoop = default(bool?), System.TimeSpan? start = default(System.TimeSpan?), System.TimeSpan? end = default(System.TimeSpan?), System.TimeSpan? fadeInDuration = default(System.TimeSpan?), System.TimeSpan? fadeOutDuration = default(System.TimeSpan?), double? audioGainLevel = default(double?))
            : base(inputLabel, inputLoop, start, end, fadeInDuration, fadeOutDuration, audioGainLevel)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
