// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The Audio Analyzer preset applies a pre-defined set of AI-based
    /// analysis operations, including speech transcription, on the input.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.AudioAnalyzerPreset")]
    public partial class AudioAnalyzerPreset : Preset
    {
        /// <summary>
        /// Initializes a new instance of the AudioAnalyzerPreset class.
        /// </summary>
        public AudioAnalyzerPreset()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AudioAnalyzerPreset class.
        /// </summary>
        /// <param name="audioLanguage">Specifies the language for the audio
        /// payload in the input. Typically in the format of "language
        /// code-country/region" (e.g: "en-US").</param>
        public AudioAnalyzerPreset(string audioLanguage = default(string))
        {
            AudioLanguage = audioLanguage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets specifies the language for the audio payload in the
        /// input. Typically in the format of "language code-country/region"
        /// (e.g: "en-US").
        /// </summary>
        [JsonProperty(PropertyName = "audioLanguage")]
        public string AudioLanguage { get; set; }

    }
}
