// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// This represents a layer in the BmpImage class.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.BmpLayer")]
    public partial class BmpLayer : Layer
    {
        /// <summary>
        /// Initializes a new instance of the BmpLayer class.
        /// </summary>
        public BmpLayer()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BmpLayer class.
        /// </summary>
        /// <param name="width">Gets or sets width of video in pixels for this
        /// layer.</param>
        /// <param name="height">Gets or sets height of video in pixels for
        /// this layer.</param>
        /// <param name="condition">Gets or sets the predicate to be evaluated
        /// before encoding this layer.</param>
        /// <param name="label">Gets or sets the label for this layer.</param>
        public BmpLayer(string width = default(string), string height = default(string), string condition = default(string), string label = default(string))
            : base(width, height, condition, label)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
