// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Describes a built-in preset for encoding the input video with the
    /// Standard Encoder.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.BuiltInStandardEncoderPreset")]
    public partial class BuiltInStandardEncoderPreset : Preset
    {
        /// <summary>
        /// Initializes a new instance of the BuiltInStandardEncoderPreset
        /// class.
        /// </summary>
        public BuiltInStandardEncoderPreset()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BuiltInStandardEncoderPreset
        /// class.
        /// </summary>
        /// <param name="presetName">Describes the built-in prese to be used
        /// for encoding videos. Possible values include: 'AdaptiveStreaming',
        /// 'AACGoodQualityAudio', 'H264MultipleBitrate1080p',
        /// 'H264MultipleBitrate720p', 'H264MultipleBitrateSD'</param>
        public BuiltInStandardEncoderPreset(EncoderNamedPreset presetName)
        {
            PresetName = presetName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets describes the built-in prese to be used for encoding
        /// videos. Possible values include: 'AdaptiveStreaming',
        /// 'AACGoodQualityAudio', 'H264MultipleBitrate1080p',
        /// 'H264MultipleBitrate720p', 'H264MultipleBitrateSD'
        /// </summary>
        [JsonProperty(PropertyName = "presetName")]
        public EncoderNamedPreset PresetName { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
