// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Describes the basic properties of all codecs.
    /// </summary>
    public partial class Codec
    {
        /// <summary>
        /// Initializes a new instance of the Codec class.
        /// </summary>
        public Codec()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Codec class.
        /// </summary>
        /// <param name="label">Describes the optional label for the
        /// codec.</param>
        public Codec(string label = default(string))
        {
            Label = label;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets describes the optional label for the codec.
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

    }
}
