// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using System.Linq;

    /// <summary>
    /// Base class for Content Key Policy key for token validation. A derived
    /// class must be used to create a token key.
    /// </summary>
    public partial class ContentKeyPolicyRestrictionTokenKey
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ContentKeyPolicyRestrictionTokenKey class.
        /// </summary>
        public ContentKeyPolicyRestrictionTokenKey()
        {
            CustomInit();
        }


        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
