// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using System.Linq;

    /// <summary>
    /// Base class for Content Key Policy restrictions. A derived class must be
    /// used to create a restriction.
    /// </summary>
    public partial class ContentKeyPolicyRestriction
    {
        /// <summary>
        /// Initializes a new instance of the ContentKeyPolicyRestriction
        /// class.
        /// </summary>
        public ContentKeyPolicyRestriction()
        {
            CustomInit();
        }


        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
