// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Represents a configuration for non-DRM keys.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.ContentKeyPolicyClearKeyConfiguration")]
    public partial class ContentKeyPolicyClearKeyConfiguration : ContentKeyPolicyConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ContentKeyPolicyClearKeyConfiguration class.
        /// </summary>
        public ContentKeyPolicyClearKeyConfiguration()
        {
            CustomInit();
        }


        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
