// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Specifies that the content key ID is in the PlayReady header.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.ContentKeyPolicyPlayReadyContentEncryptionKeyFromHeader")]
    public partial class ContentKeyPolicyPlayReadyContentEncryptionKeyFromHeader : ContentKeyPolicyPlayReadyContentKeyLocation
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ContentKeyPolicyPlayReadyContentEncryptionKeyFromHeader class.
        /// </summary>
        public ContentKeyPolicyPlayReadyContentEncryptionKeyFromHeader()
        {
            CustomInit();
        }


        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
