// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Represents a ContentKeyPolicyConfiguration that is unavailable in the
    /// current API version.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.ContentKeyPolicyUnknownConfiguration")]
    public partial class ContentKeyPolicyUnknownConfiguration : ContentKeyPolicyConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ContentKeyPolicyUnknownConfiguration class.
        /// </summary>
        public ContentKeyPolicyUnknownConfiguration()
        {
            CustomInit();
        }


        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
