// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Specifies a certificate for token validation.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.ContentKeyPolicyX509CertificateTokenKey")]
    public partial class ContentKeyPolicyX509CertificateTokenKey : ContentKeyPolicyRestrictionTokenKey
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ContentKeyPolicyX509CertificateTokenKey class.
        /// </summary>
        public ContentKeyPolicyX509CertificateTokenKey()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// ContentKeyPolicyX509CertificateTokenKey class.
        /// </summary>
        /// <param name="rawBody">The raw data field of a certificate in PKCS
        /// 12 format (X509Certificate2 in .NET)</param>
        public ContentKeyPolicyX509CertificateTokenKey(byte[] rawBody)
        {
            RawBody = rawBody;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the raw data field of a certificate in PKCS 12 format
        /// (X509Certificate2 in .NET)
        /// </summary>
        [JsonProperty(PropertyName = "rawBody")]
        public byte[] RawBody { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RawBody == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "RawBody");
            }
        }
    }
}
