// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;

    using System.Reflection;

    /// <summary>
    /// Defines values for ContentKeyPolicyRestrictionTokenType.
    /// </summary>
    public sealed class ContentKeyPolicyRestrictionTokenTypeConverter : JsonConverter
    {

        /// <summary>
        /// Returns if objectType can be converted to
        /// ContentKeyPolicyRestrictionTokenType by the converter.
        /// </summary>
        public override bool CanConvert(System.Type objectType)
        {
            return typeof(ContentKeyPolicyRestrictionTokenType).GetTypeInfo().IsAssignableFrom(objectType.GetTypeInfo());
        }

        /// <summary>
        /// Overrides ReadJson and converts token to
        /// ContentKeyPolicyRestrictionTokenType.
        /// </summary>
        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == Newtonsoft.Json.JsonToken.Null)
            {
                return null;
            }
            return (ContentKeyPolicyRestrictionTokenType)serializer.Deserialize<string>(reader);
        }

        /// <summary>
        /// Overriding WriteJson for ContentKeyPolicyRestrictionTokenType for
        /// serialization.
        /// </summary>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteValue(value.ToString());
        }

    }
}
