// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// video copy codec.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.CopyVideo")]
    public partial class CopyVideo : Codec
    {
        /// <summary>
        /// Initializes a new instance of the CopyVideo class.
        /// </summary>
        public CopyVideo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CopyVideo class.
        /// </summary>
        /// <param name="label">Gets or sets the codec label.</param>
        public CopyVideo(string label = default(string))
            : base(label)
        {
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
