// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// The HLS configuration.
    /// </summary>
    public partial class Hls
    {
        /// <summary>
        /// Initializes a new instance of the Hls class.
        /// </summary>
        public Hls()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Hls class.
        /// </summary>
        /// <param name="fragmentsPerTsSegment">The amount of fragments per
        /// HTTP Live Streaming (HLS) segment.</param>
        public Hls(int? fragmentsPerTsSegment = default(int?))
        {
            FragmentsPerTsSegment = fragmentsPerTsSegment;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the amount of fragments per HTTP Live Streaming (HLS)
        /// segment.
        /// </summary>
        [JsonProperty(PropertyName = "fragmentsPerTsSegment")]
        public int? FragmentsPerTsSegment { get; set; }

    }
}
