// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represents Job Inputs that can have a start or end time specified to
    /// take a subset of the specified media.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.JobInputClip")]
    public partial class JobInputClip : JobInput
    {
        /// <summary>
        /// Initializes a new instance of the JobInputClip class.
        /// </summary>
        public JobInputClip()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JobInputClip class.
        /// </summary>
        /// <param name="label">Label of the JobInput.  Used to match JobInputs
        /// to TransformInputs.  If no Label is given then the JobInputs are
        /// matched by index.</param>
        /// <param name="files">List of files.  Required for JobInputAzureBlob.
        /// It optionally can be used for JobInputAsset to tell the service to
        /// only use the files specified from the Asset.</param>
        public JobInputClip(string label = default(string), IList<string> files = default(IList<string>))
            : base(label)
        {
            Files = files;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets list of files.  Required for JobInputAzureBlob. It
        /// optionally can be used for JobInputAsset to tell the service to
        /// only use the files specified from the Asset.
        /// </summary>
        [JsonProperty(PropertyName = "files")]
        public IList<string> Files { get; set; }

    }
}
