// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Base class for inputs to a Job.
    /// </summary>
    public partial class JobInput
    {
        /// <summary>
        /// Initializes a new instance of the JobInput class.
        /// </summary>
        public JobInput()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JobInput class.
        /// </summary>
        /// <param name="label">Customer provided label of the
        /// JobInput.</param>
        public JobInput(string label = default(string))
        {
            Label = label;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets customer provided label of the JobInput.
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

    }
}
