// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Describes the settings to produce a JPEG image from the input video.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.JpgLayer")]
    public partial class JpgLayer : Layer
    {
        /// <summary>
        /// Initializes a new instance of the JpgLayer class.
        /// </summary>
        public JpgLayer()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JpgLayer class.
        /// </summary>
        /// <param name="width">Describes the width of the output video for
        /// this layer. The value can be absolute (in pixels) or relative (in
        /// percentage). For example 50% means the output video has half as
        /// many pixels in width as the input.</param>
        /// <param name="height">Describes the height of the output video for
        /// this layer. The value can be absolute (in pixels) or relative (in
        /// percentage). For example 50% means the output video has half as
        /// many pixels in height as the input.</param>
        /// <param name="label">Describes the alphanumeric label for this
        /// layer, which can be used in multiplexing different video and audio
        /// layers, or in naming the output file.</param>
        /// <param name="quality">Describes the compression quality of the JPEG
        /// output. Range is from 0-100 and the default is 70.</param>
        public JpgLayer(string width = default(string), string height = default(string), string label = default(string), int? quality = default(int?))
            : base(width, height, label)
        {
            Quality = quality;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets describes the compression quality of the JPEG output.
        /// Range is from 0-100 and the default is 70.
        /// </summary>
        [JsonProperty(PropertyName = "quality")]
        public int? Quality { get; set; }

    }
}
