// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Class of response for listContentKeys action
    /// </summary>
    public partial class ListContentKeysResponse
    {
        /// <summary>
        /// Initializes a new instance of the ListContentKeysResponse class.
        /// </summary>
        public ListContentKeysResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ListContentKeysResponse class.
        /// </summary>
        /// <param name="contentKeys">ContentKeys used by current Streaming
        /// Locator</param>
        public ListContentKeysResponse(IList<StreamingLocatorContentKey> contentKeys = default(IList<StreamingLocatorContentKey>))
        {
            ContentKeys = contentKeys;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets contentKeys used by current Streaming Locator
        /// </summary>
        [JsonProperty(PropertyName = "contentKeys")]
        public IList<StreamingLocatorContentKey> ContentKeys { get; set; }

    }
}
