// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for LiveEventEncodingType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum LiveEventEncodingType
    {
        [EnumMember(Value = "None")]
        None,
        [EnumMember(Value = "Basic")]
        Basic
    }
    internal static class LiveEventEncodingTypeEnumExtension
    {
        internal static string ToSerializedValue(this LiveEventEncodingType? value)
        {
            return value == null ? null : ((LiveEventEncodingType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this LiveEventEncodingType value)
        {
            switch( value )
            {
                case LiveEventEncodingType.None:
                    return "None";
                case LiveEventEncodingType.Basic:
                    return "Basic";
            }
            return null;
        }

        internal static LiveEventEncodingType? ParseLiveEventEncodingType(this string value)
        {
            switch( value )
            {
                case "None":
                    return LiveEventEncodingType.None;
                case "Basic":
                    return LiveEventEncodingType.Basic;
            }
            return null;
        }
    }
}
