// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// GOP aligned multi bitrate output.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.MultiBitrateFormat")]
    public partial class MultiBitrateFormat : Format
    {
        /// <summary>
        /// Initializes a new instance of the MultiBitrateFormat class.
        /// </summary>
        public MultiBitrateFormat()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MultiBitrateFormat class.
        /// </summary>
        /// <param name="filenamePattern">Gets or sets the pattern of the
        /// filename to use excluding the extension. REVIEW: List "macros" that
        /// can be used and give examples.</param>
        /// <param name="manifestFilename">Gets or sets the pattern of the
        /// manifest file name to use excluding the extension. REVIEW: List
        /// "macros" that can be used and give examples.</param>
        /// <param name="outputFiles">Gets the list of output files.</param>
        public MultiBitrateFormat(string filenamePattern = default(string), string manifestFilename = default(string), IList<OutputFile> outputFiles = default(IList<OutputFile>))
            : base(filenamePattern)
        {
            ManifestFilename = manifestFilename;
            OutputFiles = outputFiles;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the pattern of the manifest file name to use excluding
        /// the extension. REVIEW: List "macros" that can be used and give
        /// examples.
        /// </summary>
        [JsonProperty(PropertyName = "manifestFilename")]
        public string ManifestFilename { get; set; }

        /// <summary>
        /// Gets the list of output files.
        /// </summary>
        [JsonProperty(PropertyName = "outputFiles")]
        public IList<OutputFile> OutputFiles { get; set; }

    }
}
