// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Represent an output file.
    /// </summary>
    public partial class OutputFile
    {
        /// <summary>
        /// Initializes a new instance of the OutputFile class.
        /// </summary>
        public OutputFile()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OutputFile class.
        /// </summary>
        /// <param name="trackLabels">Gets the track labels.</param>
        public OutputFile(IList<string> trackLabels = default(IList<string>))
        {
            TrackLabels = trackLabels;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets the track labels.
        /// </summary>
        [JsonProperty(PropertyName = "trackLabels")]
        public IList<string> TrackLabels { get; set; }

    }
}
