// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using System.Linq;

    /// <summary>
    /// Base type for all Presets, which define the recipe or instructions on
    /// how the input media files should be processed.
    /// </summary>
    public partial class Preset
    {
        /// <summary>
        /// Initializes a new instance of the Preset class.
        /// </summary>
        public Preset()
        {
            CustomInit();
        }


        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

    }
}
