// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Class to specify properties of content key
    /// </summary>
    public partial class StreamingPolicyContentKey
    {
        /// <summary>
        /// Initializes a new instance of the StreamingPolicyContentKey class.
        /// </summary>
        public StreamingPolicyContentKey()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the StreamingPolicyContentKey class.
        /// </summary>
        /// <param name="label">Label can be used to specify Content Key when
        /// creating Stremaing Locator</param>
        /// <param name="policyName">Policy used by Content Key</param>
        /// <param name="tracks">Tracks which use this content key</param>
        public StreamingPolicyContentKey(string label = default(string), string policyName = default(string), IList<TrackSelection> tracks = default(IList<TrackSelection>))
        {
            Label = label;
            PolicyName = policyName;
            Tracks = tracks;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets label can be used to specify Content Key when creating
        /// Stremaing Locator
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// Gets or sets policy used by Content Key
        /// </summary>
        [JsonProperty(PropertyName = "policyName")]
        public string PolicyName { get; set; }

        /// <summary>
        /// Gets or sets tracks which use this content key
        /// </summary>
        [JsonProperty(PropertyName = "tracks")]
        public IList<TrackSelection> Tracks { get; set; }

    }
}
