// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// </auto-generated>

namespace Microsoft.Media.Encoding.Rest.ArmClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Describes the basic properties for encoding a video.
    /// </summary>
    [Newtonsoft.Json.JsonObject("#Microsoft.Media.Video")]
    public partial class Video : Codec
    {
        /// <summary>
        /// Initializes a new instance of the Video class.
        /// </summary>
        public Video()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Video class.
        /// </summary>
        /// <param name="label">Describes the optional label for the
        /// codec.</param>
        /// <param name="keyFrameInterval">Describes the distance between one
        /// key frame and the next, thereby defining a GOP or group of
        /// pictures. The value should be a non-zero integer in the range [1,
        /// .., 30], specified in ISO 8601 format. The default is 2
        /// seconds.</param>
        /// <param name="stretchMode">Describes the resizing mode - how the
        /// input video will be resized to fit the desired output
        /// resolution(s). Default is AutoSize. Possible values include:
        /// 'None', 'AutoSize', 'AutoFit'</param>
        public Video(string label = default(string), System.TimeSpan? keyFrameInterval = default(System.TimeSpan?), StretchMode? stretchMode = default(StretchMode?))
            : base(label)
        {
            KeyFrameInterval = keyFrameInterval;
            StretchMode = stretchMode;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets describes the distance between one key frame and the
        /// next, thereby defining a GOP or group of pictures. The value should
        /// be a non-zero integer in the range [1, .., 30], specified in ISO
        /// 8601 format. The default is 2 seconds.
        /// </summary>
        [JsonProperty(PropertyName = "keyFrameInterval")]
        public System.TimeSpan? KeyFrameInterval { get; set; }

        /// <summary>
        /// Gets or sets describes the resizing mode - how the input video will
        /// be resized to fit the desired output resolution(s). Default is
        /// AutoSize. Possible values include: 'None', 'AutoSize', 'AutoFit'
        /// </summary>
        [JsonProperty(PropertyName = "stretchMode")]
        public StretchMode? StretchMode { get; set; }

    }
}
